FEATURE_COLUMNS = [
    "age",
    "waiting_days",
    "sms_received_flag",
    "is_weekend",
    "transport_distance_km",
    "travel_time_minutes",
    "sentiment_score",
    "historical_no_show_rate",
    "past_visits_count",
    "past_no_show_count",
    "last_visit_gap_days",
    "num_reminders",
    "chronic_illness_flag",
    "appointment_period",
    "appointment_weekday",
    "age_group",
    "distance_category",
    "booking_channel",
    "weather_condition",
    "sentiment_label",
    "gender",
    "neighbourhood",
]

NUMERIC_FEATURES = [
    "age",
    "waiting_days",
    "sms_received_flag",
    "is_weekend",
    "transport_distance_km",
    "travel_time_minutes",
    "sentiment_score",
    "historical_no_show_rate",
    "past_visits_count",
    "past_no_show_count",
    "last_visit_gap_days",
    "num_reminders",
    "chronic_illness_flag",
]

CATEGORICAL_FEATURES = [
    "appointment_period",
    "appointment_weekday",
    "age_group",
    "distance_category",
    "booking_channel",
    "weather_condition",
    "sentiment_label",
    "gender",
    "neighbourhood",
]
